'use strict';
const $=id=>document.getElementById(id),metrics={realgdp:'PIB real',l:'Población',tau:'Productividad',u:'Utilidad / bienestar',total_trade:'Comercio total',w:'Salarios',openness:'Apertura comercial'},names={base:'Base (archivo de fronteras)',primer:'Primer escenario',segundo:'Segundo escenario',tercer:'Tercer escenario',ca_02:'CA-02',ca_09:'CA-09',ca_09_02:'CA-09 + CA-02'};
let datasets=[],visible=[],page=60,active=null,layer,gridLayer;
const map=L.map('map',{preferCanvas:true}).setView([-15,-65],4);L.control.scale({imperial:false}).addTo(map);
map.createPane('geography');map.getPane('geography').style.zIndex=250;
map.createPane('countryLabels');map.getPane('countryLabels').style.zIndex=450;map.getPane('countryLabels').style.pointerEvents='none';
const streets=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap contributors</a>',maxZoom:19});
const satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{attribution:'Imagery © Esri and contributors',maxZoom:18});
streets.addTo(map);
let geography,countryLabels=L.layerGroup().addTo(map),tileErrors=0;
[streets,satellite].forEach(t=>t.on('tileerror',()=>{tileErrors++;if(tileErrors>=3){map.removeLayer(t);$('basemap').value='local';if(geography)geography.setStyle({fillOpacity:1});$('coverage').textContent='Fondo regional integrado activo';}}));
$('basemap').onchange=()=>{[streets,satellite].forEach(t=>map.removeLayer(t));tileErrors=0;const mode=$('basemap').value;if(geography)geography.setStyle({fillOpacity:mode==='local'?1:0});if(mode==='streets')streets.addTo(map);if(mode==='satellite')satellite.addTo(map)};
$('opacity').oninput=()=>render();
$('fullscreen').onclick=()=>{const el=document.querySelector('.map-shell');el.classList.toggle('expanded-map');$('fullscreen').textContent=el.classList.contains('expanded-map')?'Cerrar mapa ×':'Ampliar mapa ⛶';setTimeout(()=>map.invalidateSize(),100)};
const descriptions={realgdp:'Resultado de PIB real reportado para cada celda. El archivo no especifica si es total o por habitante.',l:'Distribución de población entre celdas. Etiqueta interpretada a partir del código l; pendiente de validación con el diccionario del modelo.',tau:'Productividad de la celda. Etiqueta interpretada a partir del código τ; pendiente de validación con el diccionario del modelo.',u:'Utilidad o bienestar de los residentes. Etiqueta interpretada a partir del código u; pendiente de validación con el diccionario del modelo.',total_trade:'Resultado de comercio total de cada celda. No distingue importaciones y exportaciones en el archivo.',w:'Resultado salarial reportado por el modelo para cada celda.',openness:'Resultado de apertura comercial de la celda. La fórmula de este índice no está incluida en los archivos.'};
const anchors={'Argentina':[-39,-64],'Brasil':[-11,-50],'Bolivia':[-17,-64],'Chile':[-33,-73],'Perú':[-10,-76],'Paraguay':[-23,-58],'Uruguay':[-33,-56],'Ecuador':[-1,-79],'Colombia':[5,-73],'Venezuela':[8,-65],'México':[24,-103],'Guatemala':[15.5,-90.5],'Belice':[17.2,-88.5],'Honduras':[14.8,-86.5],'El Salvador':[13.7,-89],'Nicaragua':[12.8,-85],'Costa Rica':[9.8,-84],'Panamá':[8.6,-80],'Cuba':[22,-79],'Guyana':[5,-59],'Surinam':[4,-56]};
fetch('data/countries.json').then(r=>r.json()).then(g=>{geography=L.geoJSON(g,{pane:'geography',interactive:false,style:{color:'#9baea8',weight:1.1,fillColor:'#eeeede',fillOpacity:$('basemap').value==='local'?1:0}}).addTo(map);for(const [name,coord] of Object.entries(anchors)){const div=document.createElement('span');div.textContent=name;L.marker(coord,{pane:'countryLabels',interactive:false,icon:L.divIcon({className:'country-label',html:div.outerHTML,iconSize:[110,18],iconAnchor:[55,9]})}).addTo(countryLabels)}map.attributionControl.addAttribution('Límites © Natural Earth')}).catch(()=>{$('coverage').textContent='No se pudo cargar el fondo regional';});
function ds(){return datasets[+$('dataset').value]}
function key(s=$('scenario').value){return s+(ds().prefix?'_'+ds().prefix:'')+'_'+$('metric').value}
function val(r,s){const x=r[key(s)];return typeof x==='number'&&Number.isFinite(x)?x*Number($('unit').value):null}
function fmt(x){if(x===null||!Number.isFinite(x))return 'Sin dato';const n=Number($('decimals').value);return x.toLocaleString('es-CO',{minimumFractionDigits:n,maximumFractionDigits:n})}
function options(id,list){$(id).replaceChildren(...list.map(([value,label])=>{const o=document.createElement('option');o.value=value;o.textContent=label;return o}))}
function initDataset(){options('scenario',ds().scenarios.map(s=>[s,names[s]]));options('country',[['','Todos los países'],...Array.from(new Set(ds().rows.map(r=>r.country))).sort().map(c=>[c,c])]);$('country').value='';$('search').value='';page=60;active=null;render();map.fitBounds([[13.65,-92.35],[16.25,-88.05]],{padding:[25,25]})}
function color(v,extent){if(v===null)return '#b6bdb9';let t=extent?Math.min(Math.abs(v)/extent,1):0;let end=v<0?[67,107,176]:[180,73,50];return 'rgb('+end.map((c,i)=>Math.round([245,244,237][i]*(1-t)+c*t)).join(',')+')'}
function render(fit=false){$('indicatorname').textContent=metrics[$('metric').value];$('indicatorhelp').textContent=descriptions[$('metric').value];$('indicatorcode').textContent='Columna de origen: '+key();visible=ds().rows.filter(r=>(!$('country').value||r.country===$('country').value)&&r.cell.toLowerCase().includes($('search').value.trim().toLowerCase()));const nums=visible.map(r=>val(r)).filter(v=>v!==null),mn=nums.length?Math.min(...nums):null,mx=nums.length?Math.max(...nums):null,extent=Math.max(Math.abs(mn||0),Math.abs(mx||0));$('n').textContent=visible.length;$('min').textContent=fmt(mn);$('max').textContent=fmt(mx);$('avg').textContent=fmt(nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:null);$('maptitle').textContent=ds().label+' / '+names[$('scenario').value];$('coverage').textContent=visible.length+' celdas · '+metrics[$('metric').value];$('range').textContent=fmt(-extent)+' → '+fmt(extent);$('count').textContent=nums.length+' valores disponibles';
if(layer)map.removeLayer(layer);layer=L.featureGroup();visible.forEach(r=>{let v=val(r),c=color(v,extent),shape=r.geometry?L.geoJSON(r.geometry,{style:{color:'#566b65',weight:.45,fillColor:c,fillOpacity:Number($('opacity').value)/100}}):L.circleMarker([r.latitud,r.longitud],{radius:6,color:'#183e3e',fillColor:c,fillOpacity:1,weight:2});shape.bindTooltip(r.cell+' · '+r.country+' · '+fmt(v));shape.on('click',()=>select(r));layer.addLayer(shape)});layer.addTo(map);if(fit&&visible.length)map.fitBounds(layer.getBounds(),{padding:[20,20],maxZoom:7});const missing=visible.filter(r=>!r.geometry).length;$('geonote').textContent=missing?missing+' celdas no coinciden con Celdas_Gra; se muestran como puntos en las coordenadas originales.':'Todas las celdas de esta selección coinciden con la geometría de Celdas_Gra.';renderBars(extent);renderAnalysis();if(active&&visible.includes(active))select(active,false);else{$('detailtitle').textContent='Selecciona una celda';$('detailtext').textContent='Haz clic en el mapa o en una fila para comparar los escenarios del indicador activo.';$('comparison').replaceChildren()}}
function select(r,popup=true){active=r;$('detailtitle').textContent=r.cell+' · '+r.country;$('detailtext').textContent=metrics[$('metric').value]+' · '+(r.geometry?'Geometría original de Celdas_Gra':'Punto del Excel: sin coincidencia geométrica');$('comparison').replaceChildren(...ds().scenarios.map(s=>{let div=document.createElement('div');div.className='comp';let a=document.createElement('span');a.textContent=names[s];let b=document.createElement('b');b.textContent=fmt(val(r,s));div.append(a,b);return div}));if(popup){const box=document.createElement('div');let title=document.createElement('b');title.textContent=r.cell+' · '+r.country;let p=document.createElement('p');p.textContent=metrics[$('metric').value]+': '+fmt(val(r));let note=document.createElement('small');note.textContent=r.geometry?'Celda de la base geográfica':'Centro del Excel; sin polígono asociado';box.append(title,p,note);L.popup().setLatLng([r.latitud,r.longitud]).setContent(box).openOn(map)}}
function renderBars(extent){$('bars').replaceChildren(...visible.filter(r=>val(r)!==null).sort((a,b)=>Math.abs(val(b))-Math.abs(val(a))).slice(0,10).map(r=>{let row=document.createElement('div');row.className='barrow';let label=document.createElement('span');label.textContent=r.cell+' · '+r.country;row.tabIndex=0;row.setAttribute('role','button');row.setAttribute('aria-label','Localizar '+r.cell+' en '+r.country);row.onclick=()=>locate(r);row.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();locate(r)}};let wrap=document.createElement('div');let bar=document.createElement('div');bar.className='bar';bar.style.width=(extent?Math.abs(val(r))/extent*100:0)+'%';bar.style.background=color(val(r),extent);wrap.append(bar);let value=document.createElement('b');value.textContent=fmt(val(r));row.append(label,wrap,value);return row}))}
$('dataset').onchange=initDataset;['scenario','metric','unit','decimals'].forEach(id=>$(id).onchange=()=>render());$('country').onchange=()=>{page=60;render(true)};$('search').oninput=()=>{page=60;render(true)};$('reset').onclick=()=>{if(visible.length)map.fitBounds(layer.getBounds(),{padding:[20,20]})};$('grid').onchange=async()=>{if($('grid').checked){if(!gridLayer){try{let g=await fetch('data/grid.json').then(r=>r.json());gridLayer=L.geoJSON(g,{style:{color:'#78918a',weight:.4,fillOpacity:0},interactive:false})}catch(e){$('geonote').textContent='No se pudo cargar la malla completa.';return}}if($('grid').checked){gridLayer.addTo(map);gridLayer.bringToBack()}}else if(gridLayer)map.removeLayer(gridLayer)};
$('export').onclick=()=>{const esc=x=>'"'+String(x??'').replaceAll('"','""')+'"';let lines=[['celda','pais','latitud','longitud','ejercicio','escenario','indicador','factor_presentacion','valor'],...visible.map(r=>[r.cell,r.country,r.latitud,r.longitud,ds().label,$('scenario').value,$('metric').value,$('unit').value,val(r)])];let blob=new Blob(['\ufeff'+lines.map(r=>r.map(esc).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='atlas_seleccion.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
(async()=>{try{const response=await fetch('data/results.json');if(!response.ok)throw Error('datos');datasets=await response.json();options('dataset',datasets.map((d,i)=>[i,d.label]));options('metric',Object.entries(metrics));initDataset()}catch(e){$('maptitle').textContent='No se pudieron cargar los resultados. Recarga la página.';console.error(e)}})();

function locate(r){document.getElementById('explorar').scrollIntoView({behavior:'smooth',block:'start'});map.invalidateSize();map.flyTo([r.latitud,r.longitud],7,{duration:.7});select(r);}
function renderAnalysis(){
 const rows=visible.filter(r=>val(r)!==null),metric=metrics[$('metric').value],scenario=names[$('scenario').value];
 $('analysistitle').textContent=scenario+' · '+metric;
 const paragraphs=[];
 if(!rows.length){paragraphs.push('No hay valores disponibles para esta selección.');$('countrytable').replaceChildren();}
 else{
  const positive=rows.filter(r=>val(r)>0).length,negative=rows.filter(r=>val(r)<0).length,zero=rows.length-positive-negative;
  paragraphs.push('En '+scenario+', '+metric.toLowerCase()+' presenta valores positivos en '+positive+' celdas, negativos en '+negative+' y cero en '+zero+'. La selección abarca '+new Set(rows.map(r=>r.country)).size+' países.');
  const sorted=[...rows].sort((a,b)=>val(a)-val(b)),lo=sorted[0],hi=sorted[sorted.length-1];
  paragraphs.push('El mayor valor se ubica en '+hi.cell+' ('+hi.country+'): '+fmt(val(hi))+'. El menor corresponde a '+lo.cell+' ('+lo.country+'): '+fmt(val(lo))+'.');
  const gt=rows.filter(r=>r.country.toLowerCase()==='guatemala'),other=rows.filter(r=>r.country.toLowerCase()!=='guatemala');
  if(gt.length&&other.length)paragraphs.push('En Guatemala, '+gt.filter(r=>val(r)>0).length+' de '+gt.length+' celdas tienen valores positivos. Fuera de Guatemala, '+other.filter(r=>val(r)>0).length+' de '+other.length+' presentan valores positivos: el escenario muestra resultados más allá del territorio intervenido.');
  const groups=new Map();rows.forEach(r=>{if(!groups.has(r.country))groups.set(r.country,[]);groups.get(r.country).push(r)});
  $('countrytable').replaceChildren(...[...groups].sort((a,b)=>a[0].localeCompare(b[0])).map(([country,rs])=>{const tr=document.createElement('tr'),pos=rs.filter(r=>val(r)>0).length,neg=rs.filter(r=>val(r)<0).length;[country,rs.length,pos,neg,rs.length-pos-neg,fmt(rs.reduce((sum,r)=>sum+val(r),0)/rs.length)].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.append(td)});tr.title='Ver '+country+' en el mapa';tr.tabIndex=0;tr.onclick=()=>{$('country').value=country;page=60;render(true);$('explorar').scrollIntoView({behavior:'smooth'})};tr.onkeydown=e=>{if(e.key==='Enter')tr.click()};return tr}));
  const units=Number($('unit').value)===100?'Valores presentados con factor ×100.':'Valores presentados en la escala original.';paragraphs.push(units+' El signo indica la dirección del resultado; su interpretación económica depende del indicador.');
 }
 $('analysis').replaceChildren(...paragraphs.map(t=>{const p=document.createElement('p');p.textContent=t;return p}));
}

// Generalized reference corridors, not surveyed road geometry or intervention boundaries.
map.createPane('infrastructure');map.getPane('infrastructure').style.zIndex=470;
const infra=L.layerGroup().addTo(map);
fetch('data/roads.json').then(r=>r.json()).then(g=>{L.geoJSON(g,{pane:'infrastructure',style:{color:'white',weight:7,opacity:.9},interactive:false}).addTo(infra);L.geoJSON(g,{pane:'infrastructure',style:f=>({color:f.properties.route==='CA-09'?'#883ccb':'#e78512',weight:4,opacity:1}),onEachFeature:(f,l)=>l.bindTooltip(f.properties.route+' · '+f.properties.ref).bindPopup('<b>'+f.properties.route+'</b><p>Tramo sobre la red de OpenStreetMap, identificado como '+f.properties.ref+'. Trazado de OpenStreetMap de Guatemala; no delimita la intervención del modelo.</p>')}).addTo(infra)});
for(const port of [{name:'Puerto Quetzal',pos:[13.925,-90.787],coast:'Pacífico'},{name:'Santo Tomás de Castilla',pos:[15.695,-88.621],coast:'Caribe'},{name:'Puerto Barrios',pos:[15.727,-88.605],coast:'Caribe'}]){L.marker(port.pos,{pane:'infrastructure',icon:L.divIcon({className:'port-marker',html:'<span>⚓</span>',iconSize:[28,28],iconAnchor:[14,14]})}).bindTooltip(port.name,{direction:'top'}).bindPopup('<b>'+port.name+'</b><p>Puerto en la costa del '+port.coast+'. Ubicación aproximada para referencia territorial.</p>').addTo(infra)}
L.control.layers(null,{'CA-09, CA-02 y puertos':infra},{collapsed:false}).addTo(map);
