'use strict';
const $=id=>document.getElementById(id),metrics={realgdp:'PIB real',l:'Población',tau:'Productividad',u:'Utilidad / bienestar',total_trade:'Comercio total',w:'Salarios',openness:'Apertura comercial'},names={border_effect_base:'Fronteras · base',border_effect_02:'Fronteras · CA-02',border_effect_09:'Fronteras · CA-09',border_effect_09_02:'Fronteras · CA-02 + CA-09',no_border_02:'CA-02',no_border_09:'CA-09',no_border_09_02:'CA-02 + CA-09',base:'Base',primer:'Primer escenario',segundo:'Segundo escenario',tercer:'Tercer escenario',ca_02:'CA-02',ca_09:'CA-09',ca_09_02:'CA-09 + CA-02'};
let countryGeometry=null,countryComparisonLayer=null,selectedComparisonCountry='Guatemala';
const countryMap=L.map('countrymap',{preferCanvas:true,zoomControl:false,scrollWheelZoom:false,doubleClickZoom:false,boxZoom:false,touchZoom:false,dragging:false,keyboard:false,zoomSnap:0}).setView([13,-85],4);
function centerCountryComparison(){countryMap.fitBounds([[7,-93],[18.5,-77]],{padding:[16,16],animate:false})}
countryMap.on('resize',centerCountryComparison);centerCountryComparison();
let datasets=[],visible=[],page=60,active=null,layer,gridLayer;
const map=L.map('map',{preferCanvas:true}).setView([-15,-65],4);L.control.scale({imperial:false}).addTo(map);
map.createPane('geography');map.getPane('geography').style.zIndex=250;
map.createPane('countryLabels');map.getPane('countryLabels').style.zIndex=450;map.getPane('countryLabels').style.pointerEvents='none';
const streets=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap contributors</a>',maxZoom:19});
const satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{attribution:'Imagery © Esri and contributors',maxZoom:18});
streets.addTo(map);
let geography,countryLabels=L.layerGroup().addTo(map),tileErrors=0;
[streets,satellite].forEach(t=>t.on('tileerror',()=>{tileErrors++;if(tileErrors>=3){map.removeLayer(t);$('basemap').value='local';if(geography)geography.setStyle({fillOpacity:1});$('coverage').textContent='Fondo regional integrado activo';}}));
$('basemap').onchange=()=>{[streets,satellite].forEach(t=>map.removeLayer(t));tileErrors=0;const mode=$('basemap').value;if(geography)geography.setStyle({fillOpacity:mode==='local'?1:0});if(mode==='streets')streets.addTo(map);if(mode==='satellite')satellite.addTo(map)};
$('opacity').oninput=()=>render();
$('fullscreen').onclick=()=>{const el=document.querySelector('.map-shell');el.classList.toggle('expanded-map');$('fullscreen').textContent=el.classList.contains('expanded-map')?'Cerrar mapa ×':'Ampliar mapa ⛶';setTimeout(()=>map.invalidateSize(),100)};
const descriptions={realgdp:'Resultado de PIB real reportado para cada celda. El archivo no especifica si es total o por habitante.',l:'Distribución de población entre celdas. Etiqueta interpretada a partir del código l; pendiente de validación con el diccionario del modelo.',tau:'Productividad de la celda. Etiqueta interpretada a partir del código τ; pendiente de validación con el diccionario del modelo.',u:'Utilidad o bienestar de los residentes. Etiqueta interpretada a partir del código u; pendiente de validación con el diccionario del modelo.',total_trade:'Resultado de comercio total de cada celda. No distingue importaciones y exportaciones en el archivo.',w:'Resultado salarial reportado por el modelo para cada celda.',openness:'Resultado de apertura comercial de la celda. La fórmula de este índice no está incluida en los archivos.'};
const anchors={'Argentina':[-39,-64],'Brasil':[-11,-50],'Bolivia':[-17,-64],'Chile':[-33,-73],'Perú':[-10,-76],'Paraguay':[-23,-58],'Uruguay':[-33,-56],'Ecuador':[-1,-79],'Colombia':[5,-73],'Venezuela':[8,-65],'México':[24,-103],'Guatemala':[15.5,-90.5],'Belice':[17.2,-88.5],'Honduras':[14.8,-86.5],'El Salvador':[13.7,-89],'Nicaragua':[12.8,-85],'Costa Rica':[9.8,-84],'Panamá':[8.6,-80],'Cuba':[22,-79],'Guyana':[5,-59],'Surinam':[4,-56]};
fetch('data/countries.json').then(r=>r.json()).then(g=>{countryGeometry=g; if(datasets.length)renderCountryComparison();geography=L.geoJSON(g,{pane:'geography',interactive:false,style:{color:'#9baea8',weight:1.1,fillColor:'#eeeede',fillOpacity:$('basemap').value==='local'?1:0}}).addTo(map);for(const [name,coord] of Object.entries(anchors)){const div=document.createElement('span');div.textContent=name;L.marker(coord,{pane:'countryLabels',interactive:false,icon:L.divIcon({className:'country-label',html:div.outerHTML,iconSize:[110,18],iconAnchor:[55,9]})}).addTo(countryLabels)}map.attributionControl.addAttribution('Límites © Natural Earth')}).catch(()=>{$('coverage').textContent='No se pudo cargar el fondo regional';});
function ds(){return datasets[+$('dataset').value]}
function key(s=$('scenario').value){return s+(ds().prefix?'_'+ds().prefix:'')+'_'+$('metric').value}
function val(r,s){const x=r[key(s)];return typeof x==='number'&&Number.isFinite(x)?x*Number($('unit').value):null}
function fmt(x){if(x===null||!Number.isFinite(x))return 'Sin dato';const n=Number($('decimals').value);return x.toLocaleString('es-CO',{minimumFractionDigits:n,maximumFractionDigits:n})}
function options(id,list){$(id).replaceChildren(...list.map(([value,label])=>{const o=document.createElement('option');o.value=value;o.textContent=label;return o}))}
function initDataset(){options('scenario',ds().scenarios.map(s=>[s,names[s]]));options('country',[['','Todos los países'],...Array.from(new Set(ds().rows.map(r=>r.country))).sort().map(c=>[c,countryDisplay[c]||c])]);$('country').value='';$('search').value='';page=60;active=null;render();map.fitBounds([[13.65,-92.35],[16.25,-88.05]],{padding:[25,25]})}
function color(v,extent){if(v===null)return '#b6bdb9';let t=extent?Math.min(Math.abs(v)/extent,1):0;let end=v<0?[67,107,176]:[180,73,50];return 'rgb('+end.map((c,i)=>Math.round([245,244,237][i]*(1-t)+c*t)).join(',')+')'}
function render(fit=false){$('indicatorname').textContent=metrics[$('metric').value];$('indicatorhelp').textContent=descriptions[$('metric').value];visible=ds().rows.filter(r=>(!$('country').value||r.country===$('country').value)&&r.cell.toLowerCase().includes($('search').value.trim().toLowerCase()));const nums=visible.map(r=>val(r)).filter(v=>v!==null),mn=nums.length?Math.min(...nums):null,mx=nums.length?Math.max(...nums):null,extent=Math.max(Math.abs(mn||0),Math.abs(mx||0));$('n').textContent=visible.length;$('min').textContent=fmt(mn);$('max').textContent=fmt(mx);$('avg').textContent=fmt(nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:null);$('maptitle').textContent=ds().label+' / '+names[$('scenario').value];$('coverage').textContent=visible.length+' celdas · '+metrics[$('metric').value];$('range').textContent=fmt(-extent)+' → '+fmt(extent);$('count').textContent=nums.length+' valores disponibles';
if(layer)map.removeLayer(layer);layer=L.featureGroup();visible.forEach(r=>{let v=val(r),c=color(v,extent),shape=r.geometry?L.geoJSON(r.geometry,{style:{color:'#566b65',weight:.45,fillColor:c,fillOpacity:Number($('opacity').value)/100}}):L.circleMarker([r.latitud,r.longitud],{radius:6,color:'#183e3e',fillColor:c,fillOpacity:1,weight:2});shape.bindTooltip(r.cell+' · '+r.country+' · '+fmt(v));shape.on('click',()=>select(r));layer.addLayer(shape)});layer.addTo(map);if(fit&&visible.length)map.fitBounds(layer.getBounds(),{padding:[20,20],maxZoom:7});const missing=visible.filter(r=>!r.geometry).length;$('geonote').textContent=missing?missing+' celdas no coinciden con Celdas_Gra; se muestran como puntos en las coordenadas originales.':'Todas las celdas de esta selección coinciden con la geometría de Celdas_Gra.';renderBars(extent);renderAnalysis();if(active&&visible.includes(active))select(active,false);else{$('detailtitle').textContent='Selecciona una celda';$('detailtext').textContent='Haz clic en el mapa o en una barra para comparar escenarios.';$('comparison').replaceChildren()}}
function select(r,popup=true){active=r;$('detailtitle').textContent=r.cell+' · '+r.country;$('detailtext').textContent=metrics[$('metric').value]+' · '+(r.geometry?'Geometría original de Celdas_Gra':'Punto del Excel: sin coincidencia geométrica');$('comparison').replaceChildren(...ds().scenarios.map(s=>{let div=document.createElement('div');div.className='comp';let a=document.createElement('span');a.textContent=names[s];let b=document.createElement('b');b.textContent=fmt(val(r,s));div.append(a,b);return div}));if(popup){const box=document.createElement('div');let title=document.createElement('b');title.textContent=r.cell+' · '+r.country;let p=document.createElement('p');p.textContent=metrics[$('metric').value]+': '+fmt(val(r));let note=document.createElement('small');note.textContent=r.geometry?'Celda de la base geográfica':'Centro del Excel; sin polígono asociado';box.append(title,p,note);L.popup().setLatLng([r.latitud,r.longitud]).setContent(box).openOn(map)}}
function renderBars(extent){$('bars').replaceChildren(...visible.filter(r=>val(r)!==null).sort((a,b)=>Math.abs(val(b))-Math.abs(val(a))).slice(0,10).map(r=>{let row=document.createElement('div');row.className='barrow';let label=document.createElement('span');label.textContent=r.cell+' · '+r.country;row.tabIndex=0;row.setAttribute('role','button');row.setAttribute('aria-label','Localizar '+r.cell+' en '+r.country);row.onclick=()=>locate(r);row.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();locate(r)}};let wrap=document.createElement('div');let bar=document.createElement('div');bar.className='bar';bar.style.width=(extent?Math.abs(val(r))/extent*100:0)+'%';bar.style.background=color(val(r),extent);wrap.append(bar);let value=document.createElement('b');value.textContent=fmt(val(r));row.append(label,wrap,value);return row}))}
$('dataset').onchange=initDataset;['scenario','metric','unit','decimals'].forEach(id=>$(id).onchange=()=>render());$('country').onchange=()=>{page=60;render(true)};$('search').oninput=()=>{page=60;render(true)};$('reset').onclick=()=>map.fitBounds([[13.65,-92.35],[16.25,-88.05]],{padding:[25,25]});$('grid').onchange=async()=>{if($('grid').checked){if(!gridLayer){try{let g=await fetch('data/grid.json').then(r=>r.json());gridLayer=L.geoJSON(g,{style:{color:'#78918a',weight:.4,fillOpacity:0},interactive:false})}catch(e){$('geonote').textContent='No se pudo cargar la malla completa.';return}}if($('grid').checked){gridLayer.addTo(map);gridLayer.bringToBack()}}else if(gridLayer)map.removeLayer(gridLayer)};
$('export').onclick=()=>{const esc=x=>'"'+String(x??'').replaceAll('"','""')+'"';let lines=[['celda','pais','latitud','longitud','ejercicio','escenario','indicador','factor_presentacion','valor'],...visible.map(r=>[r.cell,r.country,r.latitud,r.longitud,ds().label,$('scenario').value,$('metric').value,$('unit').value,val(r)])];let blob=new Blob(['\ufeff'+lines.map(r=>r.map(esc).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='atlas_seleccion.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
(async()=>{try{const response=await fetch('data/results.json');if(!response.ok)throw Error('datos');datasets=await response.json();options('dataset',datasets.map((d,i)=>[i,d.label]));options('metric',Object.entries(metrics));initDataset()}catch(e){$('maptitle').textContent='No se pudieron cargar los resultados. Recarga la página.';console.error(e)}})();

function locate(r){document.getElementById('explorar').scrollIntoView({behavior:'smooth',block:'start'});map.invalidateSize();map.flyTo([r.latitud,r.longitud],7,{duration:.7});select(r);}
function renderAnalysis(){
 const rows=visible.filter(r=>val(r)!==null),metric=metrics[$('metric').value],scenario=names[$('scenario').value];
 $('analysistitle').textContent=scenario+' · '+metric;
 const paragraphs=[];
 if(!rows.length){paragraphs.push('No hay valores disponibles para esta selección.');}
 else{
  const positive=rows.filter(r=>val(r)>0).length,negative=rows.filter(r=>val(r)<0).length,zero=rows.length-positive-negative;
  paragraphs.push(positive+' positivas · '+negative+' negativas · '+zero+' sin cambio');
  const sorted=[...rows].sort((a,b)=>val(a)-val(b)),lo=sorted[0],hi=sorted[sorted.length-1];
  paragraphs.push('Máximo: '+hi.cell+' · '+hi.country+' · '+fmt(val(hi)));
  paragraphs.push('Mínimo: '+lo.cell+' · '+lo.country+' · '+fmt(val(lo)));
  const gt=rows.filter(r=>r.country==='Guatemala'),other=rows.filter(r=>r.country!=='Guatemala');
  if(gt.length&&other.length)paragraphs.push('Valores positivos: Guatemala '+gt.filter(r=>val(r)>0).length+'/'+gt.length+' celdas; otros países '+other.filter(r=>val(r)>0).length+'/'+other.length+'.');

 }
 renderCountryComparison();
 $('analysis').replaceChildren(...paragraphs.map(t=>{const p=document.createElement('p');p.textContent=t;return p}));
}

// Reference roads from OpenStreetMap; not intervention boundaries.
map.createPane('infrastructure');map.getPane('infrastructure').style.zIndex=470;
const infra=L.layerGroup().addTo(map);
fetch('data/roads.json').then(r=>r.json()).then(g=>{L.geoJSON(g,{pane:'infrastructure',style:{color:'white',weight:7,opacity:.9},interactive:false}).addTo(infra);L.geoJSON(g,{pane:'infrastructure',style:f=>({color:f.properties.route==='CA-09'?'#883ccb':'#e78512',weight:4,opacity:1}),onEachFeature:(f,l)=>l.bindTooltip(f.properties.route+' · '+f.properties.ref).bindPopup('<b>'+f.properties.route+'</b><p>Tramo sobre la red de OpenStreetMap, identificado como '+f.properties.ref+'. Trazado de OpenStreetMap de Guatemala; no delimita la intervención del modelo.</p>')}).addTo(infra)});
for(const port of [{name:'Puerto Quetzal',pos:[13.925,-90.787],coast:'Pacífico'},{name:'Santo Tomás de Castilla',pos:[15.695,-88.621],coast:'Caribe'},{name:'Puerto Barrios',pos:[15.727,-88.605],coast:'Caribe'}]){L.marker(port.pos,{pane:'infrastructure',icon:L.divIcon({className:'port-marker',html:'<span>⚓</span>',iconSize:[28,28],iconAnchor:[14,14]})}).bindTooltip(port.name,{direction:'top'}).bindPopup('<b>'+port.name+'</b><p>Puerto en la costa del '+port.coast+'. Ubicación aproximada para referencia territorial.</p>').addTo(infra)}
L.control.layers(null,{'CA-09, CA-02 y puertos':infra},{collapsed:false}).addTo(map);

const countryDisplay={Belize:'Belice',Costa_Rica:'Costa Rica',El_Salvador:'El Salvador',Guatemala:'Guatemala',Honduras:'Honduras',Mexico:'México',Nicaragua:'Nicaragua',Panama:'Panamá'};
function regionalSummary(){const groups=new Map();ds().rows.forEach(r=>{if(val(r)===null)return;if(!groups.has(r.country))groups.set(r.country,[]);groups.get(r.country).push(r)});return [...groups].map(([country,rs])=>({country,label:countryDisplay[country]||country,n:rs.length,pos:rs.filter(r=>val(r)>0).length,neg:rs.filter(r=>val(r)<0).length,zero:rs.filter(r=>val(r)===0).length,mean:rs.reduce((a,r)=>a+val(r),0)/rs.length})).sort((a,b)=>a.label.localeCompare(b.label,'es'))}
function signStrip(g){const strip=document.createElement('div');strip.className='sign-strip';[[g.pos,'#b44932'],[g.neg,'#436bb0'],[g.zero,'#aebac5']].forEach(([n,c])=>{const span=document.createElement('span');span.style.width=(n/g.n*100)+'%';span.style.background=c;strip.append(span)});return strip}
function renderCountryComparison(){
 if(!datasets.length)return;const summaries=regionalSummary(),extent=Math.max(...summaries.map(g=>Math.abs(g.mean)),0);
 $('countrycaption').textContent=ds().label+' · '+names[$('scenario').value]+' · '+metrics[$('metric').value];
 if(!summaries.some(g=>g.country===selectedComparisonCountry))selectedComparisonCountry=summaries[0]?.country;
 $('countrycards').replaceChildren(...summaries.map(g=>{const button=document.createElement('button');button.className='country-card infographic-country'+(g.country===selectedComparisonCountry?' selected':'');button.setAttribute('aria-pressed',g.country===selectedComparisonCountry);button.setAttribute('aria-label',g.label+': '+g.pos+' celdas positivas, '+g.neg+' negativas y '+g.zero+' sin cambio');const title=document.createElement('strong');title.textContent=g.label;const visual=document.createElement('div');visual.className='country-visual';visual.append(countrySilhouette(g),countryDonut(g));const label=document.createElement('small');label.textContent='MEDIA POR CELDA';const mean=document.createElement('b');mean.textContent=fmt(g.mean);const counts=document.createElement('div');counts.className='infographic-counts';[['Positivas',g.pos,'positive'],['Negativas',g.neg,'negative'],['Cero',g.zero,'neutral']].forEach(([label,n,cl])=>{const item=document.createElement('span');item.className=cl;const num=document.createElement('b');num.textContent=n;const text=document.createElement('small');text.textContent=label;item.append(num,text);counts.append(item)});const note=document.createElement('small');note.className='country-total';note.textContent=g.n+' celdas · Ver país en el mapa ↗';button.append(title,visual,label,mean,counts,note);button.onclick=()=>chooseComparisonCountry(g.country,true);return button}));
 if(countryGeometry){const byLabel=new Map(summaries.map(g=>[g.label,g]));const geo={type:'FeatureCollection',features:countryGeometry.features.filter(f=>byLabel.has(f.properties.name))};const initial=!countryComparisonLayer;if(countryComparisonLayer)countryMap.removeLayer(countryComparisonLayer);countryComparisonLayer=L.geoJSON(geo,{style:f=>{const g=byLabel.get(f.properties.name);return {fillColor:color(g.mean,extent),fillOpacity:.8,stroke:false,weight:0}},onEachFeature:(f,l)=>{const g=byLabel.get(f.properties.name);l.bindTooltip(g.label,{permanent:true,direction:'center',className:'comparison-country-label'});l.on('click',()=>chooseComparisonCountry(g.country,false))}}).addTo(countryMap);if(initial)centerCountryComparison()}
 const g=summaries.find(g=>g.country===selectedComparisonCountry);$('countryfocus').replaceChildren();if(!g){$('countryfocus').textContent='Sin valores disponibles';return}
 const title=document.createElement('h4');title.textContent=g.label;const label=document.createElement('small');label.textContent='Media simple por celda';const mean=document.createElement('span');mean.className='mean';mean.textContent=fmt(g.mean);const counts=document.createElement('div');counts.className='sign-counts';[['Positivas',g.pos],['Negativas',g.neg],['Cero',g.zero]].forEach(([label,n])=>{const d=document.createElement('span');d.textContent=label+' '+n;counts.append(d)});const note=document.createElement('p');note.textContent=g.n+' celdas · '+Math.round(g.pos/g.n*100)+'% con valores positivos';const button=document.createElement('button');button.className='button';button.textContent='Explorar '+g.label+' en el mapa ↗';button.onclick=()=>{$('country').value=g.country;render(true);$('explorar').scrollIntoView({behavior:'smooth'})};$('countryfocus').append(title,label,mean,signStrip(g),counts,note,button);
}
function chooseComparisonCountry(country){selectedComparisonCountry=country;renderCountryComparison()}

function countryDonut(g){const d=document.createElement('div');d.className='country-donut';const pos=g.pos/g.n*100,neg=g.neg/g.n*100;d.style.background='conic-gradient(#b44932 0% '+pos+'%,#436bb0 '+pos+'% '+(pos+neg)+'%,#aebac5 '+(pos+neg)+'% 100%)';const center=document.createElement('div');const number=document.createElement('b');number.textContent=Math.round(pos)+'%';const label=document.createElement('small');label.textContent='positivas';center.append(number,label);d.append(center);return d}
function countrySilhouette(g){const box=document.createElement('div');box.className='country-silhouette';box.setAttribute('aria-hidden','true');const feature=countryGeometry?.features.find(f=>f.properties.name===g.label);if(!feature)return box;const polygons=feature.geometry.type==='Polygon'?[feature.geometry.coordinates]:feature.geometry.coordinates;const rings=polygons.map(p=>p[0]);const points=rings.flat();const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),scale=Math.min(100/(xmax-xmin||1),90/(ymax-ymin||1));const dx=(120-(xmax-xmin)*scale)/2,dy=(110-(ymax-ymin)*scale)/2;const path=rings.map(r=>r.map((p,i)=>(i?'L':'M')+(dx+(p[0]-xmin)*scale).toFixed(2)+','+(dy+(ymax-p[1])*scale).toFixed(2)).join(' ')+'Z').join(' ');box.innerHTML='<svg viewBox="0 0 120 110" xmlns="http://www.w3.org/2000/svg"><path d="'+path+'" fill="#c8e2f4" stroke="#0072ce" stroke-width="1.5" stroke-linejoin="round"/></svg>';return box}
