'use strict';
const $=id=>document.getElementById(id),metrics={realgdp:'PIB real',l:'Población',tau:'Productividad',u:'Utilidad / bienestar',total_trade:'Comercio total',w:'Salarios',openness:'Apertura comercial'},names={border_effect_base:'Fronteras · base',border_effect_02:'Fronteras · CA-02',border_effect_09:'Fronteras · CA-09',border_effect_09_02:'Fronteras · CA-02 + CA-09',no_border_02:'CA-02',no_border_09:'CA-09',no_border_09_02:'CA-02 + CA-09',base:'Base',primer:'Primer escenario',segundo:'Segundo escenario',tercer:'Tercer escenario',ca_02:'CA-02',ca_09:'CA-09',ca_09_02:'CA-09 + CA-02'};
let countryGeometry=null,countryComparisonLayer=null,selectedComparisonCountry='Guatemala';
const countryMap=L.map('countrymap',{preferCanvas:true,zoomControl:false,scrollWheelZoom:false,doubleClickZoom:false,boxZoom:false,touchZoom:false,dragging:false,keyboard:false,zoomSnap:0}).setView([13,-85],4);
function centerCountryComparison(){countryMap.fitBounds([[7,-93],[18.5,-77]],{padding:[16,16],animate:false})}
countryMap.on('resize',centerCountryComparison);centerCountryComparison();
let datasets=[],visible=[],page=60,active=null,layer,gridLayer;
const map=L.map('map',{preferCanvas:true}).setView([-15,-65],4);L.control.scale({imperial:false}).addTo(map);
map.createPane('geography');map.getPane('geography').style.zIndex=250;
map.createPane('countryLabels');map.getPane('countryLabels').style.zIndex=450;map.getPane('countryLabels').style.pointerEvents='none';
const streets=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap contributors</a>',maxZoom:19});
const satellite=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{attribution:'Imagery © Esri and contributors',maxZoom:18});
streets.addTo(map);
let geography,countryLabels=L.layerGroup().addTo(map),tileErrors=0;
[streets,satellite].forEach(t=>t.on('tileerror',()=>{tileErrors++;if(tileErrors>=3){map.removeLayer(t);$('basemap').value='local';if(geography)geography.setStyle({fillOpacity:1});$('coverage').textContent='Fondo regional integrado activo';}}));
$('basemap').onchange=()=>{[streets,satellite].forEach(t=>map.removeLayer(t));tileErrors=0;const mode=$('basemap').value;if(geography)geography.setStyle({fillOpacity:mode==='local'?1:0});if(mode==='streets')streets.addTo(map);if(mode==='satellite')satellite.addTo(map)};
$('opacity').oninput=()=>render();
$('fullscreen').onclick=()=>{const el=document.querySelector('.map-shell');el.classList.toggle('expanded-map');$('fullscreen').textContent=el.classList.contains('expanded-map')?'Cerrar mapa ×':'Ampliar mapa ⛶';setTimeout(()=>map.invalidateSize(),100)};
const descriptions={realgdp:'Resultado de PIB real reportado para cada celda. El archivo no especifica si es total o por habitante.',l:'Distribución de población entre celdas. Etiqueta interpretada a partir del código l; pendiente de validación con el diccionario del modelo.',tau:'Productividad de la celda. Etiqueta interpretada a partir del código τ; pendiente de validación con el diccionario del modelo.',u:'Utilidad o bienestar de los residentes. Etiqueta interpretada a partir del código u; pendiente de validación con el diccionario del modelo.',total_trade:'Resultado de comercio total de cada celda. No distingue importaciones y exportaciones en el archivo.',w:'Resultado salarial reportado por el modelo para cada celda.',openness:'Resultado de apertura comercial de la celda. La fórmula de este índice no está incluida en los archivos.'};
const anchors={'Argentina':[-39,-64],'Brasil':[-11,-50],'Bolivia':[-17,-64],'Chile':[-33,-73],'Perú':[-10,-76],'Paraguay':[-23,-58],'Uruguay':[-33,-56],'Ecuador':[-1,-79],'Colombia':[5,-73],'Venezuela':[8,-65],'México':[24,-103],'Guatemala':[15.5,-90.5],'Belice':[17.2,-88.5],'Honduras':[14.8,-86.5],'El Salvador':[13.7,-89],'Nicaragua':[12.8,-85],'Costa Rica':[9.8,-84],'Panamá':[8.6,-80],'Cuba':[22,-79],'Guyana':[5,-59],'Surinam':[4,-56]};
fetch('data/countries.json').then(r=>r.json()).then(g=>{countryGeometry=g; if(datasets.length)renderCountryComparison();geography=L.geoJSON(g,{pane:'geography',interactive:false,style:{color:'#9baea8',weight:1.1,fillColor:'#eeeede',fillOpacity:$('basemap').value==='local'?1:0}}).addTo(map);for(const [name,coord] of Object.entries(anchors)){const div=document.createElement('span');div.textContent=name;L.marker(coord,{pane:'countryLabels',interactive:false,icon:L.divIcon({className:'country-label',html:div.outerHTML,iconSize:[110,18],iconAnchor:[55,9]})}).addTo(countryLabels)}map.attributionControl.addAttribution('Límites © Natural Earth')}).catch(()=>{$('coverage').textContent='No se pudo cargar el fondo regional';});
function ds(){return datasets[+$('dataset').value]}
function key(s=$('scenario').value){return s+(ds().prefix?'_'+ds().prefix:'')+'_'+$('metric').value}
function val(r,s){const x=r[key(s)];return typeof x==='number'&&Number.isFinite(x)?x*Number($('unit').value):null}
function fmt(x){if(x===null||!Number.isFinite(x))return 'Sin dato';const n=Number($('decimals').value);return x.toLocaleString('es-CO',{minimumFractionDigits:n,maximumFractionDigits:n})}
function options(id,list){$(id).replaceChildren(...list.map(([value,label])=>{const o=document.createElement('option');o.value=value;o.textContent=label;return o}))}
function initDataset(){options('scenario',ds().scenarios.map(s=>[s,names[s]]));options('country',[['','Todos los países'],...Array.from(new Set(ds().rows.map(r=>r.country))).sort().map(c=>[c,countryDisplay[c]||c])]);$('country').value='';$('search').value='';page=60;active=null;render();map.fitBounds([[13.65,-92.35],[16.25,-88.05]],{padding:[25,25]})}
function color(v,extent){if(v===null)return '#b6bdb9';let t=extent?Math.min(Math.abs(v)/extent,1):0;let end=v<0?[67,107,176]:[180,73,50];return 'rgb('+end.map((c,i)=>Math.round([245,244,237][i]*(1-t)+c*t)).join(',')+')'}
function render(fit=false){$('indicatorname').textContent=metrics[$('metric').value];$('indicatorhelp').textContent=descriptions[$('metric').value];visible=ds().rows.filter(r=>(!$('country').value||r.country===$('country').value)&&r.cell.toLowerCase().includes($('search').value.trim().toLowerCase()));const nums=visible.map(r=>val(r)).filter(v=>v!==null),mn=nums.length?Math.min(...nums):null,mx=nums.length?Math.max(...nums):null,extent=Math.max(Math.abs(mn||0),Math.abs(mx||0));$('n').textContent=visible.length;$('min').textContent=fmt(mn);$('max').textContent=fmt(mx);$('avg').textContent=fmt(nums.length?nums.reduce((a,b)=>a+b,0)/nums.length:null);$('maptitle').textContent=ds().label+' / '+names[$('scenario').value];$('coverage').textContent=visible.length+' celdas · '+metrics[$('metric').value];$('range').textContent=fmt(-extent)+' → '+fmt(extent);$('count').textContent=nums.length+' valores disponibles';
if(layer)map.removeLayer(layer);layer=L.featureGroup();visible.forEach(r=>{let v=val(r),c=color(v,extent),shape=r.geometry?L.geoJSON(r.geometry,{style:{color:'#566b65',weight:.45,fillColor:c,fillOpacity:Number($('opacity').value)/100}}):L.circleMarker([r.latitud,r.longitud],{radius:6,color:'#183e3e',fillColor:c,fillOpacity:1,weight:2});shape.bindTooltip(r.cell+' · '+r.country+' · '+fmt(v));shape.on('click',()=>select(r));layer.addLayer(shape)});layer.addTo(map);if(fit&&visible.length)map.fitBounds(layer.getBounds(),{padding:[20,20],maxZoom:7});const missing=visible.filter(r=>!r.geometry).length;$('geonote').textContent=missing?missing+' celdas no coinciden con Celdas_Gra; se muestran como puntos en las coordenadas originales.':'Todas las celdas de esta selección coinciden con la geometría de Celdas_Gra.';renderBars(extent);renderAnalysis();}
function select(r,popup=true){active=r;if(popup){const box=document.createElement('div');const title=document.createElement('b');title.textContent=r.cell+' · '+(countryDisplay[r.country]||r.country);const value=document.createElement('p');value.textContent=metrics[$('metric').value]+': '+fmt(val(r));box.append(title,value);L.popup().setLatLng([r.latitud,r.longitud]).setContent(box).openOn(map)}}
function renderBars(extent){$('bars').replaceChildren(...visible.filter(r=>val(r)!==null).sort((a,b)=>Math.abs(val(b))-Math.abs(val(a))).slice(0,10).map(r=>{let row=document.createElement('div');row.className='barrow';let label=document.createElement('span');label.textContent=r.cell+' · '+r.country;row.tabIndex=0;row.setAttribute('role','button');row.setAttribute('aria-label','Localizar '+r.cell+' en '+r.country);row.onclick=()=>locate(r);row.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();locate(r)}};let wrap=document.createElement('div');let bar=document.createElement('div');bar.className='bar';bar.style.width=(extent?Math.abs(val(r))/extent*100:0)+'%';bar.style.background=color(val(r),extent);wrap.append(bar);let value=document.createElement('b');value.textContent=fmt(val(r));row.append(label,wrap,value);return row}))}
$('dataset').onchange=initDataset;['scenario','metric','unit','decimals'].forEach(id=>$(id).onchange=()=>render());$('country').onchange=()=>{page=60;render(true)};$('search').oninput=()=>{page=60;render(true)};$('reset').onclick=()=>map.fitBounds([[13.65,-92.35],[16.25,-88.05]],{padding:[25,25]});$('grid').onchange=async()=>{if($('grid').checked){if(!gridLayer){try{let g=await fetch('data/grid.json').then(r=>r.json());gridLayer=L.geoJSON(g,{style:{color:'#78918a',weight:.4,fillOpacity:0},interactive:false})}catch(e){$('geonote').textContent='No se pudo cargar la malla completa.';return}}if($('grid').checked){gridLayer.addTo(map);gridLayer.bringToBack()}}else if(gridLayer)map.removeLayer(gridLayer)};
$('export').onclick=()=>{const esc=x=>'"'+String(x??'').replaceAll('"','""')+'"';let lines=[['celda','pais','latitud','longitud','ejercicio','escenario','indicador','factor_presentacion','valor'],...visible.map(r=>[r.cell,r.country,r.latitud,r.longitud,ds().label,$('scenario').value,$('metric').value,$('unit').value,val(r)])];let blob=new Blob(['\ufeff'+lines.map(r=>r.map(esc).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='atlas_seleccion.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
(async()=>{try{const response=await fetch('data/results.json');if(!response.ok)throw Error('datos');datasets=await response.json();options('dataset',datasets.map((d,i)=>[i,d.label]));options('metric',Object.entries(metrics));initDataset();initScenarioComparison()}catch(e){$('maptitle').textContent='No se pudieron cargar los resultados. Recarga la página.';console.error(e)}})();

function locate(r){document.getElementById('explorar').scrollIntoView({behavior:'smooth',block:'start'});map.invalidateSize();map.flyTo([r.latitud,r.longitud],7,{duration:.7});select(r);}
function renderAnalysis(){
 const rows=visible.filter(r=>val(r)!==null),metric=metrics[$('metric').value],scenario=names[$('scenario').value];
 $('analysistitle').textContent=scenario+' · '+metric;
 const paragraphs=[];
 if(!rows.length){paragraphs.push('No hay valores disponibles para esta selección.');}
 else{
  const positive=rows.filter(r=>val(r)>0).length,negative=rows.filter(r=>val(r)<0).length,zero=rows.length-positive-negative;
  paragraphs.push(positive+' positivas · '+negative+' negativas · '+zero+' sin cambio');
  const sorted=[...rows].sort((a,b)=>val(a)-val(b)),lo=sorted[0],hi=sorted[sorted.length-1];
  paragraphs.push('Máximo: '+hi.cell+' · '+hi.country+' · '+fmt(val(hi)));
  paragraphs.push('Mínimo: '+lo.cell+' · '+lo.country+' · '+fmt(val(lo)));
  const gt=rows.filter(r=>r.country==='Guatemala'),other=rows.filter(r=>r.country!=='Guatemala');
  if(gt.length&&other.length)paragraphs.push('Valores positivos: Guatemala '+gt.filter(r=>val(r)>0).length+'/'+gt.length+' celdas; otros países '+other.filter(r=>val(r)>0).length+'/'+other.length+'.');

 }
 if(compareReady)renderScenarioComparison();
 renderCountryComparison();
 $('analysis').replaceChildren(...paragraphs.map(t=>{const p=document.createElement('p');p.textContent=t;return p}));
}

// Reference roads from OpenStreetMap; not intervention boundaries.
map.createPane('infrastructure');map.getPane('infrastructure').style.zIndex=470;
const infra=L.layerGroup().addTo(map);
fetch('data/roads.json').then(r=>r.json()).then(g=>{L.geoJSON(g,{pane:'infrastructure',style:{color:'white',weight:7,opacity:.9},interactive:false}).addTo(infra);L.geoJSON(g,{pane:'infrastructure',style:f=>({color:f.properties.route==='CA-09'?'#883ccb':'#e78512',weight:4,opacity:1}),onEachFeature:(f,l)=>l.bindTooltip(f.properties.route+' · '+f.properties.ref).bindPopup('<b>'+f.properties.route+'</b><p>Tramo sobre la red de OpenStreetMap, identificado como '+f.properties.ref+'. Trazado de OpenStreetMap de Guatemala; no delimita la intervención del modelo.</p>')}).addTo(infra)});
for(const port of [{name:'Puerto Quetzal',pos:[13.925,-90.787],coast:'Pacífico'},{name:'Santo Tomás de Castilla',pos:[15.695,-88.621],coast:'Caribe'},{name:'Puerto Barrios',pos:[15.727,-88.605],coast:'Caribe'}]){L.marker(port.pos,{pane:'infrastructure',icon:L.divIcon({className:'port-marker',html:'<span>⚓</span>',iconSize:[28,28],iconAnchor:[14,14]})}).bindTooltip(port.name,{direction:'top'}).bindPopup('<b>'+port.name+'</b><p>Puerto en la costa del '+port.coast+'. Ubicación aproximada para referencia territorial.</p>').addTo(infra)}
L.control.layers(null,{'CA-09, CA-02 y puertos':infra},{collapsed:false}).addTo(map);

const countryDisplay={Belize:'Belice',Costa_Rica:'Costa Rica',El_Salvador:'El Salvador',Guatemala:'Guatemala',Honduras:'Honduras',Mexico:'México',Nicaragua:'Nicaragua',Panama:'Panamá'};
function regionalSummary(){const groups=new Map();ds().rows.forEach(r=>{if(val(r)===null)return;if(!groups.has(r.country))groups.set(r.country,[]);groups.get(r.country).push(r)});return [...groups].map(([country,rs])=>({country,label:countryDisplay[country]||country,n:rs.length,pos:rs.filter(r=>val(r)>0).length,neg:rs.filter(r=>val(r)<0).length,zero:rs.filter(r=>val(r)===0).length,mean:rs.reduce((a,r)=>a+val(r),0)/rs.length})).sort((a,b)=>a.label.localeCompare(b.label,'es'))}
function signStrip(g){const strip=document.createElement('div');strip.className='sign-strip';[[g.pos,'#b44932'],[g.neg,'#436bb0'],[g.zero,'#aebac5']].forEach(([n,c])=>{const span=document.createElement('span');span.style.width=(n/g.n*100)+'%';span.style.background=c;strip.append(span)});return strip}
function renderCountryComparison(){
 if(!datasets.length)return;const summaries=regionalSummary(),extent=Math.max(...summaries.map(g=>Math.abs(g.mean)),0);
 $('countrycaption').textContent=ds().label+' · '+names[$('scenario').value]+' · '+metrics[$('metric').value];
 if(!summaries.some(g=>g.country===selectedComparisonCountry))selectedComparisonCountry=summaries[0]?.country;
 $('countrycards').replaceChildren(...summaries.map(g=>{const button=document.createElement('button');button.className='country-card infographic-country'+(g.country===selectedComparisonCountry?' selected':'');button.setAttribute('aria-pressed',g.country===selectedComparisonCountry);button.setAttribute('aria-label',g.label+': '+g.pos+' celdas positivas, '+g.neg+' negativas y '+g.zero+' sin cambio');const title=document.createElement('strong');title.textContent=g.label;const visual=document.createElement('div');visual.className='country-visual';visual.append(countrySilhouette(g),countryDonut(g));const label=document.createElement('small');label.textContent='MEDIA POR CELDA';const mean=document.createElement('b');mean.textContent=fmt(g.mean);const counts=document.createElement('div');counts.className='infographic-counts';[['Positivas',g.pos,'positive'],['Negativas',g.neg,'negative'],['Cero',g.zero,'neutral']].forEach(([label,n,cl])=>{const item=document.createElement('span');item.className=cl;const num=document.createElement('b');num.textContent=n;const text=document.createElement('small');text.textContent=label;item.append(num,text);counts.append(item)});const note=document.createElement('small');note.className='country-total';note.textContent=g.n+' celdas · Ver país en el mapa ↗';button.append(title,visual,label,mean,counts,note);button.onclick=()=>chooseComparisonCountry(g.country,true);return button}));
 if(countryGeometry){const byLabel=new Map(summaries.map(g=>[g.label,g]));const geo={type:'FeatureCollection',features:countryGeometry.features.filter(f=>byLabel.has(f.properties.name))};const initial=!countryComparisonLayer;if(countryComparisonLayer)countryMap.removeLayer(countryComparisonLayer);countryComparisonLayer=L.geoJSON(geo,{style:f=>{const g=byLabel.get(f.properties.name);return {fillColor:color(g.mean,extent),fillOpacity:.8,stroke:false,weight:0}},onEachFeature:(f,l)=>{const g=byLabel.get(f.properties.name);l.bindTooltip(g.label,{permanent:true,direction:'center',className:'comparison-country-label'});l.on('click',()=>chooseComparisonCountry(g.country,false))}}).addTo(countryMap);if(initial)centerCountryComparison()}

}
function chooseComparisonCountry(country){selectedComparisonCountry=country;renderCountryComparison()}

function countryDonut(g){const d=document.createElement('div');d.className='country-donut';const pos=g.pos/g.n*100,neg=g.neg/g.n*100;d.style.background='conic-gradient(#b44932 0% '+pos+'%,#436bb0 '+pos+'% '+(pos+neg)+'%,#aebac5 '+(pos+neg)+'% 100%)';const center=document.createElement('div');const number=document.createElement('b');number.textContent=Math.round(pos)+'%';const label=document.createElement('small');label.textContent='positivas';center.append(number,label);d.append(center);return d}
function countrySilhouette(g){const box=document.createElement('div');box.className='country-silhouette';box.setAttribute('aria-hidden','true');const feature=countryGeometry?.features.find(f=>f.properties.name===g.label);if(!feature)return box;const polygons=feature.geometry.type==='Polygon'?[feature.geometry.coordinates]:feature.geometry.coordinates;const rings=polygons.map(p=>p[0]);const points=rings.flat();const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys),scale=Math.min(100/(xmax-xmin||1),90/(ymax-ymin||1));const dx=(120-(xmax-xmin)*scale)/2,dy=(110-(ymax-ymin)*scale)/2;const path=rings.map(r=>r.map((p,i)=>(i?'L':'M')+(dx+(p[0]-xmin)*scale).toFixed(2)+','+(dy+(ymax-p[1])*scale).toFixed(2)).join(' ')+'Z').join(' ');box.innerHTML='<svg viewBox="0 0 120 110" xmlns="http://www.w3.org/2000/svg"><path d="'+path+'" fill="#c8e2f4" stroke="#0072ce" stroke-width="1.5" stroke-linejoin="round"/></svg>';return box}

const compareMaps=['compareMapA','compareMapB','compareMapD'].map(id=>L.map(id,{preferCanvas:true,scrollWheelZoom:false,zoomSnap:0}).setView([15,-90],6));
let compareLayers=[],compareReady=false,compareSync=false;
compareMaps.forEach(m=>{m.createPane('compareGeography');m.getPane('compareGeography').style.zIndex=250});
let compareGeographyReady=false;
compareMaps.forEach(m=>m.on('moveend',()=>{if(compareSync)return;compareSync=true;compareMaps.forEach(other=>{if(other!==m)other.setView(m.getCenter(),m.getZoom(),{animate:false})});compareSync=false}));
function compareHome(){compareMaps.forEach(m=>m.fitBounds([[7,-94],[19,-77]],{padding:[12,12],animate:false}))}
$('comparehome').onclick=compareHome;
function initScenarioComparison(){const choices=datasets.flatMap((d,i)=>d.scenarios.map(s=>[i+'|'+s,d.label+' · '+names[s]]));options('compareA',choices);options('compareB',choices);$('compareB').value='0|ca_09';options('compareMetric',Object.entries(metrics));options('compareCountry',[['','Todos los países'],...Array.from(new Set(datasets.flatMap(d=>d.rows.map(r=>r.country)))).sort().map(c=>[c,countryDisplay[c]||c])]);['compareA','compareB','compareMetric','compareCountry'].forEach(id=>$(id).onchange=renderScenarioComparison);compareReady=true;compareHome();renderScenarioComparison()}
function comparisonPairs(){const [ai,as]=$('compareA').value.split('|'),[bi,bs]=$('compareB').value.split('|'),a=datasets[+ai],b=datasets[+bi],metric=$('compareMetric').value,factor=Number($('unit').value),column=(d,s)=>s+(d.prefix?'_'+d.prefix:'')+'_'+metric;const lookup=new Map(b.rows.map(r=>[r.country+'|'+r.cell,r]));return a.rows.flatMap(r=>{const t=lookup.get(r.country+'|'+r.cell),av=r[column(a,as)],bv=t?.[column(b,bs)];return t&&Number.isFinite(av)&&Number.isFinite(bv)?[{r,a:av*factor,b:bv*factor,d:(bv-av)*factor}]:[]})}
function renderScenarioComparison(){if(!compareReady)return;if(countryGeometry&&!compareGeographyReady){compareMaps.forEach(m=>L.geoJSON(countryGeometry,{pane:'compareGeography',interactive:false,style:{fillColor:'#e1eaf2',fillOpacity:1,color:'#a4b8ca',weight:.6}}).addTo(m));compareGeographyReady=true;}const all=comparisonPairs(),pairs=all.filter(x=>!$('compareCountry').value||x.r.country===$('compareCountry').value),extent=Math.max(0,...pairs.flatMap(x=>[Math.abs(x.a),Math.abs(x.b)])),delta=Math.max(0,...pairs.map(x=>Math.abs(x.d)));$('compareTitleA').textContent='A · '+$('compareA').children[+$('compareA').selectedIndex]?.textContent;$('compareTitleB').textContent='B · '+$('compareB').children[+$('compareB').selectedIndex]?.textContent;
compareMaps.forEach((m,i)=>{if(compareLayers[i])m.removeLayer(compareLayers[i]);const group=L.featureGroup();pairs.forEach(x=>{const k=['a','b','d'][i],v=x[k],c=color(v,i===2?delta:extent),shape=x.r.geometry?L.geoJSON(x.r.geometry,{style:{color:'#52677c',weight:.5,fillColor:c,fillOpacity:.75}}):L.circleMarker([x.r.latitud,x.r.longitud],{radius:5,color:c,fillOpacity:1});shape.bindTooltip(x.r.cell+' · '+(countryDisplay[x.r.country]||x.r.country)+' · '+fmt(v));shape.on('click',()=>{const box=document.createElement('div');box.textContent=x.r.cell+' · '+(countryDisplay[x.r.country]||x.r.country)+' | A: '+fmt(x.a)+' | B: '+fmt(x.b)+' | B − A: '+fmt(x.d);L.popup().setLatLng([x.r.latitud,x.r.longitud]).setContent(box).openOn(m)});group.addLayer(shape)});compareLayers[i]=group.addTo(m)});
$('compareScale').textContent=pairs.length+' celdas comparables · Azul: negativo; rojo: positivo · Escala común A/B: '+fmt(-extent)+' a '+fmt(extent)+' · Diferencias: '+fmt(-delta)+' a '+fmt(delta);
const groups=new Map();pairs.forEach(x=>{if(!groups.has(x.r.country))groups.set(x.r.country,[]);groups.get(x.r.country).push(x)});renderComparisonTable(groups);if(!pairs.length)$('compareCards').textContent='Sin celdas comparables para esta selección.';
}

function comparisonCountryCard(country,rs){
 const card=document.createElement('article');card.className='compare-infographic';const label=countryDisplay[country]||country;const means=Object.fromEntries(['a','b','d'].map(k=>[k,rs.reduce((s,x)=>s+x[k],0)/rs.length]));const up=rs.filter(x=>x.d>0).length,down=rs.filter(x=>x.d<0).length,zero=rs.length-up-down;
 const head=document.createElement('div');head.className='compare-country-head';const title=document.createElement('h4');title.textContent=label;const total=document.createElement('small');total.textContent=rs.length+' celdas';head.append(title,total,countrySilhouette({label}));
 const change=document.createElement('div');change.className='compare-change '+(means.d>0?'up':means.d<0?'down':'unchanged');const tag=document.createElement('small');tag.textContent='DIFERENCIA MEDIA · B − A';const number=document.createElement('strong');number.textContent=(means.d>0?'+':'')+fmt(means.d);const direction=document.createElement('span');direction.textContent=means.d>0?'↑ Aumenta de A a B':means.d<0?'↓ Disminuye de A a B':'= Sin cambio medio';change.append(tag,number,direction);
 const plot=document.createElement('div');plot.className='compare-dumbbell';const lo=Math.min(0,means.a,means.b),hi=Math.max(0,means.a,means.b),extent=hi-lo||1,position=v=>18+(v-lo)/extent*244,ax=position(means.a),bx=position(means.b),zx=position(0);plot.innerHTML='<svg viewBox="0 0 280 62" role="img" aria-label="Posición de los valores medios A y B respecto de cero"><line x1="18" x2="262" y1="30" y2="30" stroke="#dce6ef" stroke-width="4"/><line x1="'+zx+'" x2="'+zx+'" y1="12" y2="44" stroke="#8da3b6" stroke-dasharray="3 3"/><line x1="'+ax+'" x2="'+bx+'" y1="30" y2="30" stroke="#0072ce" stroke-width="5"/><circle cx="'+ax+'" cy="30" r="7" fill="#fff" stroke="#003b71" stroke-width="3"/><circle cx="'+bx+'" cy="30" r="7" fill="#0072ce" stroke="#fff" stroke-width="2"/><text x="'+zx+'" y="58" text-anchor="middle" font-size="10" fill="#52677c">0</text></svg>';
 const values=document.createElement('div');values.className='compare-values';[['A',means.a],['B',means.b]].forEach(([name,value])=>{const box=document.createElement('div');const lab=document.createElement('span');lab.textContent=name;const n=document.createElement('b');n.textContent=fmt(value);box.append(lab,n);values.append(box)});
 const strip=signStrip({n:rs.length,pos:up,neg:down,zero});const counts=document.createElement('div');counts.className='compare-direction-counts';[['↑ Suben',up,'#b44932'],['↓ Bajan',down,'#436bb0'],['= Igual',zero,'#6c7c8a']].forEach(([label,n,color])=>{const box=document.createElement('div');const num=document.createElement('b');num.textContent=n;num.style.color=color;const lab=document.createElement('small');lab.textContent=label;box.append(num,lab);counts.append(box)});card.append(head,change,plot,values,strip,counts);return card;
}


let comparisonSort={column:0,direction:1};
function comparisonTableRows(groups){return [...groups].map(([country,rs])=>{const means=['a','b','d'].map(k=>rs.reduce((s,x)=>s+x[k],0)/rs.length),up=rs.filter(x=>x.d>0).length,down=rs.filter(x=>x.d<0).length;return [countryDisplay[country]||country,...means,up,down,rs.length-up-down,rs.length]}).sort((a,b)=>{const k=comparisonSort.column;const cmp=k===0?a[0].localeCompare(b[0],'es'):a[k]-b[k];return cmp*comparisonSort.direction||a[0].localeCompare(b[0],'es')})}
function renderComparisonTable(groups){const wrap=document.createElement('div');wrap.className='table-wrap compare-table-wrap';const table=document.createElement('table');const caption=document.createElement('caption');caption.textContent='Haz clic en un encabezado para ordenar ↑ de menor a mayor o ↓ de mayor a menor.';table.append(caption);const thead=document.createElement('thead');const headings=document.createElement('tr');['País','Media A','Media B','Diferencia B − A','Suben ↑','Bajan ↓','Sin cambio','Celdas'].forEach((label,i)=>{const th=document.createElement('th');th.setAttribute('scope','col');th.setAttribute('aria-sort',comparisonSort.column===i?(comparisonSort.direction===1?'ascending':'descending'):'none');const button=document.createElement('button');button.className='sort-column';button.textContent=label+' '+(comparisonSort.column===i?(comparisonSort.direction===1?'↑':'↓'):'↕');button.title='Ordenar por '+label;button.onclick=()=>{comparisonSort.direction=comparisonSort.column===i?-comparisonSort.direction:1;comparisonSort.column=i;renderComparisonTable(groups)};th.append(button);headings.append(th)});thead.append(headings);const body=document.createElement('tbody');comparisonTableRows(groups).forEach(row=>{const tr=document.createElement('tr');row.forEach((value,i)=>{const td=document.createElement('td');td.textContent=i>=1&&i<=3?(i===3&&value>0?'+':'')+fmt(value):value;if(i===3)td.className='delta-cell '+(value>0?'delta-up':value<0?'delta-down':'delta-zero');tr.append(td)});body.append(tr)});table.append(thead,body);wrap.append(table);$('compareCards').replaceChildren(wrap)}
